1-.

#!/usr/bin/perl
# your code goes here

use strict;
use warnings;
use 5.010


sub init{
   
    my $contador;

    sub incrementar {
        $contador++;
    }
   

}


2-.

(defvar regular 5)
(print regular)
(setq regular 6)
(print regular)

(defvar tmp 2)
(print tmp)
(defvar tmp 8)
(print tmp)


3-.

function fun1(var num1)
{
var dentro;
	function fun2(var num2){
		num2 = num2 + 2;
		dentro = num2;
		console.log(dentro);
	}
	

	function fun3(var num3){
		dentro = num3 + 10;
		console.log(dentro);
	}

dentro =  50;
console.log(dentro);

}


4-.

def fun2(num2):
		num2 = num2 + 2
		dentro = num2
		print "valor de dentro en fun1 ", dentro
		


def fun3(num3):
		dentro = num3 + 10
		print " valor de dentro en fun2" , dentro


def fun1(num1):
	dentro = 0
	fun2(dentro)
	fun3(dentro)

	dentro =  50
	print "valor dentro fuera de las subfunciones" , dentro

fun1(5)

5-.


	C: 	"error: 'x' undeclared" la variable se determina como irreconocida al no tener un tipo, retornando un error 
	C++: 	"error: 'x' was not declared in this scope" la variable se determina como irreconocida al no tener un tipo, retornando un error 
	Java: 	"cannot find symbol" la variable no se reconoce al no tener tipo definido retornando error 

6 -.

----C# y c++

int j = 0;
for(int i  = 0; i < 5; i++){
	int prueba;
	j = i;
	prueba = j;
}

cout<< prueba;
cout<< j;

--C++

prog.cpp:13:8: error: 'prueba' was not declared in this scope


--C#
prog.cs(15,22): error CS0103: The name `prueba' does not exist in the current context


---java---

int j = 0;
for(int i  = 0; i < 5; i++){
	int prueba;
	j = i;
	prueba = j;
}

system.out.printf(prueba);
system.out.printf(j);

Main.java:20: error: cannot find symbol

7-.


Hello world!
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

std::bad_alloc es una excepcion que indica que nos quedamos sin memoria

